---
title: "Scratch"
author: "Andreas Beger, Predictive Heuristics"
date: "3/1/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Levels of Torture 

Ordinal scale with 6 regular values and 6 special values:

1. No Allegations
2. Infrequent
3. Several
4. Routinely
5. Widespread
6. Systematic

- Continued
- Improved
- Increased/Worsening
- Allegation, no LoT
- -777 central government collapse
- -999 foreign state occupation

```{r}
library("tidyverse")
library("haven")

allegations <- read_dta("input/itt/data/RevisedSAFINAL_11Mar2013.dta")


cy <- read_csv("input/itt/data/CY.csv")
cyvt <- read_csv("input/itt/data/CYVT.csv")
cyaocvt <- read_csv("input/itt/data/CYAoCVT.csv")

ggplot(cy, aes(x = LoT)) + 
  geom_bar() +
  coord_flip()

cyvt %>%
  gather(key, value, starts_with("LoT")) %>%
  ggplot(aes(x = value)) +
  geom_bar() +
  coord_flip()

cyvt %>%
  gather(key, value, starts_with("LoT")) %>%
  ggplot(aes(x = value, group = key)) +
  geom_bar() +
  coord_flip() +
  facet_wrap(~ key)

cyvt %>%
  gather(key, value, starts_with("LoT")) %>%
  filter(value!="No Allegations") %>%
  ggplot(aes(x = value, group = key)) +
  geom_bar() +
  coord_flip() +
  facet_wrap(~ key)

cyvt %>%
  gather(key, value, starts_with("LoT")) %>%
  ggplot(aes(x = factor(cowccode), y = year, fill = value)) +
  facet_wrap(~ key) +
  geom_tile()
  
```

## Country-year, agency, victim

```{r}
tidy_cyaocvt <- cyaocvt %>%
  gather(starts_with("LoT"))
```

